services:
  ebpf:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ebpf-dev
    privileged: true
    working_dir: /home
    volumes:
      - ../home:/home
      - /lib/modules:/lib/modules:ro
    stdin_open: true
    tty: true
